[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@bisonai/orakl-contracts/=lib/orakl/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]

[rpc_endpoints]
kairos_testnet = "${KAIROS_TESTNET_RPC_URL}"
kaia_mainnet = "${KAIA_MAINNET_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
